FuchsiaCity_House2_Text_HaveYouVisitedCinnabarLab::
    .string "Hey, long time no see!\n"
    .string "Have you visited the CINNABAR\l"
    .string "LAB yet?$"

FuchsiaCity_House2_Text_YouWantTheFossil::
    .string "Hello there! Why have you\n"
    .string "come to my house?\p"
    .string "It doesn't matter, listen\n"
    .string "I have found this cool fossil\n"
    .string "at MT. MOON, but I can't\n"
    .string "take it to CINNABAR LAB.\p"
    .string "I have...hhmm...issues...\n"
    .string "...\n"
    .string "The scientists don't like me.\p"
    .string "Do you want the FOSSIL?$"

FuchsiaCity_House2_Text_ObtainedDomeFossil::
    .string "{PLAYER} obtained the DOME FOSSIL!$"

FuchsiaCity_House2_Text_ObtainedHelixFossil::
    .string "{PLAYER} obtained the HELIX FOSSIL!$"

FuchsiaCity_House2_Text_ISee::
    .string "I see…$"



