ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

ViridianCity_Mart_Text_ImFishingEnthusiast::
    .string "I'm the FISHING ENTHUSIAST!\p"
    .string "Fishing for pokemon is fun!\n"
    .string "I have just started it.\p"
    .string "So, would you like to do it too?$"

ViridianCity_Mart_Text_OhYourLoss::
    .string "Oh, no!\p"
    .string "I guess you are not interested.$"

ViridianCity_Mart_Text_HowIsFishing::
    .string "How many MAGICKARPS have you\n"
    .string "caught?\p"
    .string "I have an aquarium full of them!$"

ViridianCity_Mart_Text_NoRoomForOldRod::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

ViridianCity_Mart_Text_ReceivedOldRodFromFishingEnthusiast::
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING ENTHUSIAST.$"

ViridianCity_Mart_Text_TakeThisAndStartFishing::
    .string "Amazing! You'll love it!\p"
    .string "Take this and start fishing!$"

ViridianCity_Mart_Text_StartFishing::
    .string "You will be an Enthusiast too!\n"
    .string "Just go and start fishing!\p"
    .string "From the seas to rivers, go out\n"
    .string "and start feeling it.$"

